// data.js
const studentData = [
  {
    rollno: "22UCSE4001",
    name: "ABHINAV JAYALWAAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Abhinav@4001",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4002",
    name: "AKASH SHARMA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Akash@4002",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4003",
    name: "AMRISH KANWAT",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Amrish@4003",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4004",
    name: "ANIKET SINGH",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Aniket@4004",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4006",
    name: "ARPIT SINGHAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Arpit@4006",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4007",
    name: "ASHUTOSH SHARMA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Ashutosh@4007",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4008",
    name: "ATIKSHA SHARMA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Atiksha@4008",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4009",
    name: "BHARAT AGRAWAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Bharat@4009",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4010",
    name: "BHARAT JANGID",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Bharat@4010",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4011",
    name: "BHASKAR KATARA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Bhaskar@4011",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4012",
    name: "DEEPALI SHARMA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Deepali@4012",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4013",
    name: "DEVIN SHANESHA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Devin@4013",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4014",
    name: "DILIP JEENGAR",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Dilip@4014",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4015",
    name: "DIPTI POONIA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Dipti@4015",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4016",
    name: "HIMANI CHAWLA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Himani@4016",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4017",
    name: "KAMLESH KUMAR SAINI",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Kamlesh@4017",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4018",
    name: "KAMLESH YADAV",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "kamlesh@4018",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4019",
    name: "KHUSH PUROHIT",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Khush@4019",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4020",
    name: "KUMKUM SHARMA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Kumkum@4020",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4021",
    name: "KUNAL TAMBI",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Kunal@4021",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4022",
    name: "KUNWARDEEP SINGH",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Kunwardeep@4022",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4023",
    name: "LAKSHITA DAVE",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Lakshita@4023",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4024",
    name: "MOHIT KUMAR JINDAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Mohit@4024",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4025",
    name: "MUSKAAN AGARWAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Muskaan@4025",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4026",
    name: "NARPAT KUMAR",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Narpat@4026",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4027",
    name: "PRAKHAR JAIN",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Prakhar@4027",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4028",
    name: "PRIYA GARG",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Priya@4028",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4029",
    name: "RAHUL SINGH",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Rahul@4029",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4030",
    name: "SACHIN BARUPAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Sachin@4030",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4031",
    name: "SOHAN LAL PRAJAPAT",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Sohan@4031",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4032",
    name: "SUMAN MEENA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Suman@4032",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4033",
    name: "SWEETY",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Sweety@4033",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4034",
    name: "TEJASWANI BHARDWAJ",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Tejaswani@4034",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4035",
    name: "VANDANA SAINI",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Vandana@4035",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4036",
    name: "VANSH SHARMA",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Vansh@4036",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4037",
    name: "VARDA RAM",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Varda@4037",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4038",
    name: "VIJAY PAL",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Vijay@4038",
    degree: "B.E",
  },
  {
    rollno: "22UCSE4039",
    name: "VINAY CHOUDHARY",
    photo: null,
    branch: "CSE",
    semester: "6th",
    password: "Vinay@4039",
    degree: "B.E",
  },
];

const teacherData = [
  {
    name: "Abhishek Gour",
    teacherId: "1001",
    password: "Abhishek@1001",
    department: "CSE",
  },
  {
    name: "Anil Gupta",
    teacherId: "1002",
    password: "Anil@1002",
    department: "CSE",
  },
  {
    name: "N.C Barwar",
    teacherId: "1003",
    password: "NC@1003",
    department: "CSE",
  },
  {
    name: "Simran Choudary",
    teacherId: "1004",
    password: "Simran@1004",
    department: "CSE",
  },
];
module.exports = { studentData, teacherData };
